print("Welcome to the Elite 101 ChatBot")
print("Please enter your name: ")
name = input()
print("Nice to meet you," + name + "! How old are you? ")
age = input()
print("Welcome " + name + "! Oh, to be " + age + " again! How can I help you today")
print("Please choose from the options below: ")
print("  1. Conquer the World")
print("  2. End Poverty in the World")
print("  3. Remove hunger from the World")
print("  4. Bring Peace to the World")
print("  5. Exit this unrealistic conversation")
choice = input()
if( choice == "5"):
  print("GoodBye, " + name + "! Have a great day!")
exit()
